modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="aquatic_artifacts"
version="1.0"
displayName="Aquatic Artifacts"
logoFile="examplemod.png" #optional
credits=""
authors="Basti, Realz, Ilja, Ryorama"
description='''
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
